config/routes.rb
helios::Application.routes.draw do

	root to: "dashboards#index"

	ActiveAdmin.routes(self)
	namespace :admin_powers do
		get "new_travel_email/:id", action: "new_travel_email", as: "new_travel_email"
		get "duplicate_travel/:id", action: "duplicate_travel", as: "duplicate_travel"
	end

	scope "/:locale", :constraints => {:locale => /[a-z]{2}(-[A-Z]{2})?/} do

		root to: "dashboards#index"

		devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

		resources :dashboards

		resources :users do
			resources :travels do
				get 'cgv', :on => :member
			end
			resources :cars
			resources :rents do
				resource :payment
				get 'cgv', :on => :member
			end
		end
		resources :rents, only: [:new]
		resources :travels, only: [:new]

		authenticated :user do
			match "/travels", to: redirect { |p, req| "/#{p[:locale]}/users/#{req.env["warden"].user(:user).id}/travels/new" }, :as => 'travels'
		end

		unauthenticated :user do
			match '/travels(/:action)' => 'anonymous_travels', :as => 'travels'
		end

		match '/search(/:action)' => 'search', :as => 'search'

	end

	match "nav" => "navigations#index"
	match "log" => "navigations#log"

	resources :notifications do
		post :payment, on: :member
	end

	resources :parkings
	post '/parkings/ipn/:id' => 'parkings#ipn', as: 'parkings_ipn'
	get '/parkings/success/:id' => 'parkings#success', as: 'parkings_success'

	get "api/cars", to: "search#api_search", as: "api_search"
	get '/api/:token/travel/:travel', to: 'search#api_redirect', as: 'api_redirect'

end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController

	def index
		respond_to do |format|
			unless current_user.nil?
				format.js
			else
				format.js { render :nothing => true, :status => 200, :content_type => "text/javascript" }
			end
		end
	end

	def log
		render text: File.read("#{Rails.root}/log/#{Rails.env}.log")
	end

end

app/views/navigations/index.js.erb
jQuery(function($){
	$('.menu-sidentifier').html('<a class="dropdown-toggle" data-toggle="dropdown" href="#"> <%= t(:account) %> <b class="caret"></b> </a> <ul class="dropdown-menu"> <li> <%= link_to t(:dashboard), dashboards_url %> </li> <li> <%= link_to t(:my_informations), edit_user_registration_url %> </li> <li> <%= link_to t(:my_travels), user_travels_url(current_user) %> </li> <li> <%= link_to t(:my_rents), user_rents_url(current_user) %> </li> </ul>');
	$('.connect-button').attr('href', '<%= dashboards_url %>').html('<i class="li_lock"></i><span>Mon compte</span>');
	$('.li_lock').attr('class', 'li_user');
});