config/routes.rb
helios::Application.routes.draw do

	root to: "dashboards#index"

	ActiveAdmin.routes(self)
	namespace :admin_powers do
		get "new_travel_email/:id", action: "new_travel_email", as: "new_travel_email"
		get "duplicate_travel/:id", action: "duplicate_travel", as: "duplicate_travel"
	end

	scope "/:locale", :constraints => {:locale => /[a-z]{2}(-[A-Z]{2})?/} do

		root to: "dashboards#index"

		devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

		resources :dashboards

		resources :users do
			resources :travels do
				get 'cgv', :on => :member
			end
			resources :cars
			resources :rents do
				resource :payment
				get 'cgv', :on => :member
			end
		end
		resources :rents, only: [:new]
		resources :travels, only: [:new]

		authenticated :user do
			match "/travels", to: redirect { |p, req| "/#{p[:locale]}/users/#{req.env["warden"].user(:user).id}/travels/new" }, :as => 'travels'
		end

		unauthenticated :user do
			match '/travels(/:action)' => 'anonymous_travels', :as => 'travels'
		end

		match '/search(/:action)' => 'search', :as => 'search'

	end

	match "nav" => "navigations#index"
	match "log" => "navigations#log"

	resources :notifications do
		post :payment, on: :member
	end

	resources :parkings
	post '/parkings/ipn/:id' => 'parkings#ipn', as: 'parkings_ipn'
	get '/parkings/success/:id' => 'parkings#success', as: 'parkings_success'

	get "api/cars", to: "search#api_search", as: "api_search"
	get '/api/:token/travel/:travel', to: 'search#api_redirect', as: 'api_redirect'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		@users = User.all
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<header id="header">
  <div class="header-holder">
    <div class="container hidden-phone">
      <div class="brow">
        <div class="brick1 logo_container">
          <a href="#" class="nav-item clearfix">
            <!--div class="nav-hover"></div-->
            <h1 class="logo image">
              <%= image_tag "helios-logo_big_image.png", :alt => "Logo" %>
            </h1>
          </a>
        </div>
      </div>
      <div class="brick3 default boffset1 slogan transparent text-right">
        <div class="inner">
          <h1>Voyagez Intelligemment !</h1>

          <p>helios est la première plateforme Européenne de partage de véhicules entre les voyageurs aux
            aéroports. D’un coté, elle permet aux propriétaires souhaitant se rendre à l’aéroport avec leur voiture non
            seulement de la garer gratuitement, mais aussi de gagner de l’argent pendant qu’ils voyagent.</p></div>
      </div>
      <div class="brick2 default ">
        <a href="<%= user_session_path %>" class="nav-item ">
          <div class="nav-hover"></div>
          <i class="li_settings"></i>
          <span>Me connecter</span>
        </a>
      </div>
      <div class="brick3 odd ">
        <%= link_to travels_url, :class => "nav-item" do %>
            <div class="nav-hover"></div>
            <i class="li_key"></i>
            <span><%= t(:register_travel) %></span>
        <% end %>
      </div>
      <div class="brick3 orange ">
        <%= link_to search_path, :class => "nav-item" do %>

            <div class="nav-hover"></div>
            <i class="li_truck"></i>
            <span><%= t(:rent_car) %></span>
        <% end %>
      </div>
      <div class="brick2 default ">
        <a href="http://localhost/helios/#pourquoi-helios" class="nav-item ">
          <div class="nav-hover"></div>
          <i class="li_bulb"></i>
          <span>Pourquoi helios ?</span>
        </a>
      </div>
      <div class="brick2 default ">
        <a href="http://localhost/helios/#besoin-daide" class="nav-item ">
          <div class="nav-hover"></div>
          <i class="li_like"></i>
          <span>Besoin d'aide ?</span>
        </a>
      </div>
      <div class="brick2 default ">
        <a href="http://localhost/helios/#contact" class="nav-item ">
          <div class="nav-hover"></div>
          <i class="li_paperplane"></i>
          <span>Contact</span>
        </a>
      </div>
    </div>
    <!-- end hidden-phone -->
    <div class="container visible-phone">
      <div class="brick1 logo_container">
        <a href="#" class="nav-item clearfix">
          <div class="nav-hover"></div>
          <h1 class="logo image">
            <%= image_tag "helios-logo_big_image.png", :alt => "Logo" %>
          </h1>
        </a>
      </div>
      <div class="brick1 odd">
        <a href="http://localhost/helios/#comment-ca-marche" class="nav-item ">
          <div class="nav-hover"></div>
          <i class="li_settings"></i>
          <span>Comment ca marche ?</span>
        </a>
      </div>
      <div class="brick1 odd ">
        <%= link_to travels_url, :class => "nav-item" do %>
            <div class="nav-hover"></div>
            <i class="li_key"></i>
            <span><%= t(:register_travel) %></span>
        <% end %>
      </div>
      <div class="brick1">
        <%= link_to search_path, :class => "nav-item" do %>

            <div class="nav-hover"></div>
            <i class="li_truck"></i>
            <span><%= t(:rent_car) %></span>
        <% end %>
      </div>
      <div class="brick1 ">
        <a href="http://localhost/helios/#pourquoi-helios" class="nav-item ">
          <div class="nav-hover"></div>
          <i class="li_bulb"></i>
          <span>Pourquoi helios ?</span>
        </a>
      </div>
      <div class="brick1 odd">
        <a href="http://localhost/helios/#besoin-daide" class="nav-item ">
          <div class="nav-hover"></div>
          <i class="li_like"></i>
          <span>Besoin d'aide ?</span>
        </a>
      </div>
      <div class="brick1 odd">
        <a href="http://localhost/helios/#contact" class="nav-item ">
          <div class="nav-hover"></div>
          <i class="li_paperplane"></i>
          <span>Contact</span>
        </a>
      </div>
    </div>
  </div>
</header>

app/views/home/index.html.erb
<% content_for :header do %>
    <%= render "header" %>
<% end %>

<% content_for :no_container do %>
    <div class="section" id="comment-ca-marche">
      <div class="container">

        <div class="hero">
          <h1>Comment ça marche ? </h1>

          <p></p>
        </div>
        <div class="entry-content">
          <p>En quelques clics, vous rajouter votre véhicule sur le site : modèle, caractéristiques et disponibilités et
            le
            tour est joué. Vous économiserez non seulement les frais de parking pendant que vous voyagez mais vous
            gagnerez
            aussi de l’argent lorsque votre voiture sera louée par un autre voyageur.</p>

          <p>Vous êtes en voyage et vous souhaitez louer une voiture à l’aéroport ? Rien de plus simple. Consultez les
            annonces de nos résidents et faites votre réservation directement en ligne.</p>

          <p>Et soyez rassurés : que vous soyez résident ou voyageur, propriétaire ou locataire, aucune démarche
            particulière n’est nécessaire, helios couvre le tout avec une assurance tous risques.</p>

          <p>Il est important de noter également que helios agit comme un vrai tiers de confiance, elle ne fait pas
            seulement la simple mise en relation entre voyageurs. helios fait l’état des lieux des véhicules,
            effectue
            les vérifications de sécurité nécessaires et gère toute la transaction jusqu’à la remise du véhicule au
            propriétaire à son retour de vacances. Nous proposons un service différent, de confiance et intelligent.</p>
        </div>
        <!-- .entry-content -->

      </div>
    </div>
    <div class="section" id="jinscris-ma-voiture">
      <div class="container">

        <div class="hero">
          <h1>Je propose ma voiture gratuitement</h1>

          <p>et j'obtiens un Parking gratuit à l’aéroport + Service de voiturier + couverture automatique avec une
            assurance
            tous risques + lavage offert</p>
        </div>
        <div class="entry-content">
          <p>Vous êtes résident et propriétaire de votre véhicule, vous souhaitez mutualiser son usage pendant que vous
            voyagez, non seulement économiser les frais de parking mais aussi gagner de l’argent en ayant un
            comportement
            solidaire et éco-responsable ?</p>

          <p>Commencez par renseigner votre aéroport ainsi que vos dates de départ et de retour. Suivez les quelques
            étapes
            afin d’enregistrer votre véhicule. A vous de jouer !</p>
        </div>
        <!-- .entry-content -->

      </div>
    </div>
    <div class="divider section">
      <div class="bg-holder">
        <div class="container">
          <div class="hero">
            <p>

            <h1>Je propose ma voiture gratuitement</h1>

            <p>
              <button class="btn btn-large" style="width:auto;" type="button">
                <div class="nav-hover"></div>
                <p>Super, j’ai un voyage prévu et je veux inscrire ma voiture</p>
              </button>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="section" id="je-loue-une-voiture">
      <div class="container">

        <div class="hero">
          <h1>Je souhaite louer une voiture </h1>

          <p>Jusqu’à 50% moins cher qu’un loueur classique, Assurance tous risques sans supplément, options gratuites
            (siège
            bébé, GPS, etc.)</p>
        </div>
        <div class="entry-content">
          <p>Vous êtes un voyageur et vous souhaitez louer une voiture ? Rien de plus simple : Renseignez votre aéroport
            ainsi que vos dates d’arrivée et de départ. Choisissez ensuite la voiture qui vous convient et valider votre
            réservation en ligne. A vous de jouer !</p>
        </div>
        <!-- .entry-content -->

      </div>
    </div>
    <div class="divider section">
      <div class="bg-holder">
        <div class="container">
          <div class="hero">
            <p>

            <h1>Je souhaite louer une voiture </h1>

            <p>
              <button class="btn btn-large" style="width:auto;" type="button">
                <div class="nav-hover"></div>
                <p>Top ! Je réserve une voiture tout de suite !
                </p>
              </button>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="section" id="pourquoi-helios">
      <div class="container">

        <div class="hero">
          <h1>helios, KESAKO ?</h1>

          <p>helios est la première plateforme Européenne de partage de véhicules entre les voyageurs aux
            aéroports.</p>
        </div>
        <div class="entry-content">
          <p>helios est la <b>première plateforme Européenne </b>de <b>partage </b>de véhicules entre les
            <b>voyageurs </b>aux <b>aéroports.</b>D’un coté, elle permet aux propriétaires souhaitant se rendre à
            l’aéroport
            avec leur voiture non seulement de la <b>garer gratuitement, </b>mais aussi de <b>gagner de l’argent </b>pendant
            qu’ils voyagent.</p>

          <p>Comment ? En louant ce véhicule aux autres voyageurs du même aéroport.</p>

          <p>De l’autre coté, ces visiteurs quant à eux, pourront <b>économiser </b>jusqu&rsquo;à 50% sur le prix
            habituellement proposé par les agences de location classique.</p>

          <p>helios <b>assure </b>le tout automatiquement avec une couverture <b>tous risques </b>et une assistance
            24h/24.</p>

          <p>Avec helios <span style="text-decoration: underline;">voyageons intelligemment</span> en
            <span style="text-decoration: underline;">mutualisant</span> l’usage de nos véhicules.</p>

          <p>helios offre non seulement <span style="text-decoration: underline;">une alternative</span> au parking
            cher de l&rsquo;aéroport et une solution économique de location de véhicules, mais permet aussi aux
            voyageurs de
            <span style="text-decoration: underline;">gagner</span> de l’argent pendant qu’ils voyagent avec un
            comportement
            <span style="text-decoration: underline;">solidaire</span> tout en aidant
            <span style="text-decoration: underline;">la planète</span>.</p>

          <p>Faisons en sorte qu’il y ait
            <span style="text-decoration: underline;">moins de nouvelles voitures fabriquées </span>et
            <span style="text-decoration: underline;">plus de places de parking</span> disponibles.</p>

          <p>Adhérer à helios c’est adhérer à une démarche
            <span style="text-decoration: underline;">responsable</span>,
            <span style="text-decoration: underline;">économique</span> et
            <span style="text-decoration: underline;">écologique</span> !</p>

          <p>23 400 particuliers font confiance aujourd’hui et partagent l’usage de leur véhicule en France, à quand le
            v^Otre ?</p>
        </div>
        <!-- .entry-content -->

      </div>
    </div>
    <div class="section" id="besoin-daide">
      <div class="container">

        <div class="hero">
          <h1>Besoin d’aide ?</h1>

          <p>Description</p>
        </div>
        <div class="entry-content">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer quis mi nisl. Quisque sed enim ut nulla
            condimentum placerat. Integer nec diam dolor, et sollicitudin justo. Lorem ipsum dolor sit amet, consectetur
            adipiscing elit. Integer nibh nisl, tempor nec gravida eu, ornare vel leo. Pellentesque habitant morbi
            tristique
            senectus et netus et malesuada fames ac turpis egestas. Etiam pretium lacus non justo malesuada sit amet
            ornare
            est feugiat. Ut sapien turpis, posuere eget viverra eu, consequat sit amet magna. Fusce eget nulla ac metus
            aliquam cursus eu sed lectus. Nulla bibendum, nisl vel dictum cursus, nisi turpis vestibulum odio, ac auctor
            tortor tortor ut dui. Nulla facilisis, mauris vitae viverra sollicitudin, ipsum dolor ornare erat,
            condimentum
            egestas turpis tellus eleifend sapien. Nam vulputate luctus consectetur. Phasellus convallis varius ante,
            vel
            lobortis orci sollicitudin at. Praesent ornare leo id mi dignissim eget rhoncus mauris euismod<br/>
            <!--p style="text-align:center"><br />
            <button class="btn btn-large" style="width:auto;" type="button">
            <div class="nav-hover"></div>
            <p>Contactez-nous</button>
            </p-->
        </div>
        <!-- .entry-content -->

      </div>
    </div>
    <div class="section" id="contact">
      <div class="container">

        <div class="hero">
          <h1>Contactez-Nous</h1>

          <p>Pour toute question ou renseignement n’hésitez pas à nous contacter !</p>
        </div>
        <div class="entry-content">
          <div class="row-fluid">
            <div class="span6">
              <div>
                <h3>contact info</h3>
                <ul>
                  <li>Address: CT3A Building street 195, New Something 1234, Country Australia</li>
                  <li>Telephone: +132.13213212 &#8211; +23.312312546</li>
                  <li>Fax: 322323</li>
                  <li>Email: joe@argo.com</li>
                </ul>
                <p>
                  <a class="social facebook" href="#"><i class="icon-facebook"></i></a><a class="social twitter" href="#"><i class="icon-twitter"></i></a><a class="social gplus" href="#"><i class="icon-google-plus"></i></a><a class="social linkedin" href="#"><i class="icon-linkedin"></i></a>
                </p>

                <div></div>
              </div>
            </div>
            <div class="span6">
              <h3>leave a reply</h3>

              <p>

              <form class="comment_form" id="commentform" method="post" action="http://localhost/helios/wp-admin/admin-ajax.php?action=contact">
                <div class="row-fluid">
                  <div class="span6">
                    <input type="email" placeholder="Email" required name="email" id="email"/>
                  </div>
                  <div class="span6">
                    <input type="text" placeholder="Name" required name="name" id="name"/>
                  </div>
                </div>
                <div class="row-fluid">
                  <div class="span8">
                    <textarea rows="10" cols="30" placeholder="Message" name="message"></textarea>
                  </div>
                  <div class="span4">
                    <button type="submit" class="btn "><i class="li_paperplane"></i>Send message</button>
                  </div>
                </div>
              </form>
              </p>
            </div>
          </div>
        </div>
        <!-- .entry-content -->

      </div>
    </div>
<% end %>