config/routes.rb
helios::Application.routes.draw do

	root to: "dashboards#index"

	ActiveAdmin.routes(self)
	namespace :admin_powers do
		get "new_travel_email/:id", action: "new_travel_email", as: "new_travel_email"
		get "duplicate_travel/:id", action: "duplicate_travel", as: "duplicate_travel"
	end

	scope "/:locale", :constraints => {:locale => /[a-z]{2}(-[A-Z]{2})?/} do

		root to: "dashboards#index"

		devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

		resources :dashboards

		resources :users do
			resources :travels do
				get 'cgv', :on => :member
			end
			resources :cars
			resources :rents do
				resource :payment
				get 'cgv', :on => :member
			end
		end
		resources :rents, only: [:new]
		resources :travels, only: [:new]

		authenticated :user do
			match "/travels", to: redirect { |p, req| "/#{p[:locale]}/users/#{req.env["warden"].user(:user).id}/travels/new" }, :as => 'travels'
		end

		unauthenticated :user do
			match '/travels(/:action)' => 'anonymous_travels', :as => 'travels'
		end

		match '/search(/:action)' => 'search', :as => 'search'

	end

	match "nav" => "navigations#index"
	match "log" => "navigations#log"

	resources :notifications do
		post :payment, on: :member
	end

	resources :parkings
	post '/parkings/ipn/:id' => 'parkings#ipn', as: 'parkings_ipn'
	get '/parkings/success/:id' => 'parkings#success', as: 'parkings_success'

	get "api/cars", to: "search#api_search", as: "api_search"
	get '/api/:token/travel/:travel', to: 'search#api_redirect', as: 'api_redirect'

end

app/models/payment.rb
class Payment < ActiveRecord::Base

	before_create :default_values
	attr_accessible :amount, :contribution_details, :contribution_id, :status

	belongs_to :rent

	STATUS = {:unpaid => 0, :pending => 1, :paid => 2, :failed => 3}

	def status
		STATUS.key(read_attribute(:status))
	end

	def status=(s)
		write_attribute(:status, STATUS[s.to_sym])
	end

	def check_payment
		if self.status == :pending
			#contribution id save ?
			self.contribution_details = Leetchi::Contribution.details(self.contribution_id)
			#check status paiement
			self.status = self.contribution_details['IsSucceeded'] ? :paid : :failed
			self.save
		end
	end

	def amount_in_euros
		self.amount/100
	end



	private

	def default_values
		self.status ||= :unpaid
	end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	include PricingHelper

	before_filter :authenticate_user!
	load_and_authorize_resource :rent
	load_and_authorize_resource :payment, :through => :rent, :singleton => true


	## GET /payments
	## GET /payments.json
	#def index
	#  @payments = Payment.all
	#
	#  respond_to do |format|
	#    format.html # index.html.erb
	#    format.json { render json: @payments }
	#  end
	#end

	# GET /payments/1
	# GET /payments/1.json
	def show
		@payment = @rent.payment

		@payment.check_payment

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @payment }
		end
	end

	# GET /payments/new
	# GET /payments/new.json
	def new
		if @rent.payment.nil?

			@payment = Payment.new
			@payment.amount = price_for_rent(@rent)

			respond_to do |format|
				format.html # new.html.erb
				format.json { render json: @payment }
			end
		else
			flash[:error] = t("payments.show.payment_existing")
			redirect_to :action => 'show'
		end
	end

	# GET /payments/1/edit
	def edit
		@payment = Payment.find(params[:id])
	end

	# POST /payments
	# POST /payments.json
	def create
		#TODO : compute price in back or verify ?
		if @rent.payment.nil?

			@payment = Payment.new
			@payment.rent = @rent
			@payment.amount = price_for_rent_in_cents(@rent)

			respond_to do |format|
				if @payment.save
					#Fix how to store / config userId Leetchi
					contribution = Leetchi::Contribution.create({"UserID" => ENV["LEETCHI_TARGET_USER_ID"],
																 "WalletID" => 0,
																 "Amount" => @payment.amount,
																 "ClientFeeAmount" => 0,
																 "RegisterMeanOfPayment" => false,
																 "ReturnURL" => user_rent_payment_url(current_user, @rent),
																 "PaymentMethodType" => "cb_visa_mastercard"})


					#save contribution id
					@payment.contribution_id = contribution["ID"]
					@payment.contribution_details = contribution
					@payment.status = :pending
					@payment.save!

					format.html { redirect_to contribution["PaymentURL"] }
					format.json { render json: @payment, status: :created, location: @payment }
				else
					format.html { render action: "new" }
					format.json { render json: @payment.errors, status: :unprocessable_entity }
				end
			end
		else
			flash[:error] = t("payments.show.payment_existing")
			redirect_to :action => 'show'
		end

	end

	# PUT /payments/1
	# PUT /payments/1.json
	def update
		@payment = Payment.find(params[:id])

		respond_to do |format|
			if @payment.update_attributes(params[:payment])
				format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @payment.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /payments/1
	# DELETE /payments/1.json
	def destroy
		@payment = Payment.find(params[:id])
		@payment.destroy

		respond_to do |format|
			format.html { redirect_to payments_url }
			format.json { head :no_content }
		end
	end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<div class="row-fluid">

  <div class="span8">
    <h1><%= [@rent.travel.car.year, @rent.travel.car.brand, @rent.travel.car.model].join(' - ') %>
    </h1>

    <%= render "cars/carroussel", :car => @rent.travel.car %>

  </div>

  <div class="span4">


    <h2><%= t(".pay_this_car") %></h2>

    <p>
      <%= t(".we_summarize") %>
    </p>

    <h3><%= t(".where") %></h3>

    <p>
      <%= @rent.travel.airPort.name %>
    </p>


    <h3><%= t(".when") %></h3>

    <p>
      <%= t :interval_datetime, :startDate => l(@rent.startDate), :endDate => l(@rent.endDate) %>
    </p>


    <h3><%= t(".how_many") %></h3>

    <p><%= [t(:x_days, :count => number_of_days(@rent)), t(:byDay, :price => number_to_currency(@rent.travel.car.category.price_in_euros))].join(", ") %>
    </p>


    <h2><%= t(:total, :total => number_to_currency(price_for_rent(@rent))) %> </h2>


    <%= form_for [current_user, @rent, @payment], url: user_rent_payment_path do |f| %>
        <%= f.submit :class => "btn btn-large on-hover btn-block" %>
    <% end %>


  </div>


</div>


<h2><%= t(".details") %></h2>

<%= render 'cars/details', :car => @rent.travel.car %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <tr>
    <th>Amount</th>
    <th>Belongs to</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.amount %></td>
    <td><%= payment.belongs_to %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1><%= t(".title") %></h1>

<%= render 'form' %>

app/views/payments/show.html.erb
<h1><%= t(".title") %></h1>

<div class="row-fluid">

  <div class="span8">
    <p>
    <%= t(".summary", :brand => @rent.travel.car.brand, :model => @rent.travel.car.model, :year => @rent.travel.car.year, :from => @rent.startDate, :to => @rent.endDate, :airPort => @rent.airPort.name ) %>
    </p>

    <p>
      <%= t(".payment_info_#{@payment.status}", :amount => number_to_currency(@payment.amount_in_euros)) %>
    </p>

    <p>
      <%= t(".thank_you") %>
    </p>
  </div>
</div>