config/routes.rb
helios::Application.routes.draw do

	root to: "dashboards#index"

	ActiveAdmin.routes(self)
	namespace :admin_powers do
		get "new_travel_email/:id", action: "new_travel_email", as: "new_travel_email"
		get "duplicate_travel/:id", action: "duplicate_travel", as: "duplicate_travel"
	end

	scope "/:locale", :constraints => {:locale => /[a-z]{2}(-[A-Z]{2})?/} do

		root to: "dashboards#index"

		devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

		resources :dashboards

		resources :users do
			resources :travels do
				get 'cgv', :on => :member
			end
			resources :cars
			resources :rents do
				resource :payment
				get 'cgv', :on => :member
			end
		end
		resources :rents, only: [:new]
		resources :travels, only: [:new]

		authenticated :user do
			match "/travels", to: redirect { |p, req| "/#{p[:locale]}/users/#{req.env["warden"].user(:user).id}/travels/new" }, :as => 'travels'
		end

		unauthenticated :user do
			match '/travels(/:action)' => 'anonymous_travels', :as => 'travels'
		end

		match '/search(/:action)' => 'search', :as => 'search'

	end

	match "nav" => "navigations#index"
	match "log" => "navigations#log"

	resources :notifications do
		post :payment, on: :member
	end

	resources :parkings
	post '/parkings/ipn/:id' => 'parkings#ipn', as: 'parkings_ipn'
	get '/parkings/success/:id' => 'parkings#success', as: 'parkings_success'

	get "api/cars", to: "search#api_search", as: "api_search"
	get '/api/:token/travel/:travel', to: 'search#api_redirect', as: 'api_redirect'

end

app/models/car.rb
class Car < ActiveRecord::Base

	attr_accessible :brand, :model, :fuel, :nbSeats, :km, :year, :license , :desc, :category_id, :transmission
	attr_accessible :hasChildSeat, :hasGps, :hasCarRadio, :isSmoker, :acceptedPets, :hasAirConditioning
	attr_accessible :filepicker1_url, :filepicker2_url, :filepicker3_url

	validates :brand,  :presence => true
	validates :model,  :presence => true
	validates :year,  :presence => true
	validates :nbSeats,  :presence => true
	validates :transmission,  :presence => true
	validates :fuel,  :presence => true

	belongs_to :travels

	belongs_to :category

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

	before_filter :load_user

	# GET /cars
	# GET /cars.json
	def index
		@cars = @user.cars.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @cars }
		end
	end

	# GET /cars/1
	# GET /cars/1.json
	def show
		@car = @user.cars.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @car }
		end
	end

	# GET /cars/new
	# GET /cars/new.json
	def new
		@car = @user.cars.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @car }
		end
	end

	# GET /cars/1/edit
	def edit
		@car = @user.cars.find(params[:id])
	end

	# POST /cars
	# POST /cars.json
	def create
		@car = @user.cars.new(params[:car])

		respond_to do |format|
			if @car.save
				format.html { redirect_to [@user,@car], notice: 'Car was successfully created.' }
				format.json { render json: @car, status: :created, location: @car }
			else
				format.html { render action: "new" }
				format.json { render json: @car.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /cars/1
	# PUT /cars/1.json
	def update
		@car = Car.find(params[:id])

		respond_to do |format|
			if @car.update_attributes(params[:car])
				format.html { redirect_to [@user,@car], notice: 'Car was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @car.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /cars/1
	# DELETE /cars/1.json
	def destroy
		@car = @user.cars.find(params[:id])
		@car.destroy

		respond_to do |format|
			format.html { redirect_to user_cars_url(@user) }
			format.json { head :no_content }
		end
	end



	private

	def load_user
		@user = User.find(params[:user_id])
	end
end

app/helpers/cars_helper.rb
module CarsHelper

	CONVERTER = {0 => '0-50000 km', 50000 => '50000-100000 km', 100000 => '100000-150000 km', 150000 => '150000 km et plus'}

	def km_to_human(km)
		CONVERTER[km]
	end

	def km_to_list
		CONVERTER.collect {|k,v| [v,k]}
	end

end

app/views/cars/_carroussel.erb
<% unless car.nil? %>
    <% images_url = [car.filepicker1_url, car.filepicker2_url, car.filepicker3_url].select { |url| !url.nil? && !url.empty? } %>
    <div class="img-polaroid" style="text-align: center">
      <% if !images_url.empty? %>
          <div id="myCarousel" class="carousel slide">
            <ol class="carousel-indicators">

              <% images_url.each_with_index do |item, index| %>
                  <li data-target="#myCarousel" data-slide-to="<%= index.to_s %>"
                      class="<%= if index == 0 then
                                   "active"
                                 end %>">

                  </li>
              <% end %>

            </ol>
            <div class="carousel-inner">
              <% images_url.each_with_index do |item, index| %>
                  <div class="item <%= if index == 0 then
                                         "active"
                                       end %>">

                    <%= filepicker_image_tag item, height: 525, fit: 'max' %>
                    <div class="carousel-caption">
                      <h4><%= [car.year, car.brand, car.model].join(' - ') %></h4>
                    </div>
                  </div>
              <% end %>
            </div>
            <% if images_url.length > 1  %>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
            <% end %>
          </div>
      <% else %>
          <i class="icon-camera-retro" style="line-height: 300px; font-size: 120px; color: graytext"></i>
      <% end %>
    </div>

<% end %>

app/views/cars/_details.html.erb
<div class="well">
  <div class="row-fluid">
    <div class="span4">

      <p>
        <b><%= t(:nbSeats, :scope => [:helpers, :label, :car]) %>:</b>
        <%= car.nbSeats %>
      </p>

      <p>
        <b><%= t(:km, :scope => [:helpers, :label, :car]) %>:</b>
        <%= km_to_human(car.km) %>
      </p>

      <p>
        <b><%= t(:fuel, :scope => [:helpers, :label, :car]) %>:</b>
        <%= t(car.fuel, :scope => [:helpers, :label, :car])  %>
      </p>

      <p>
        <b><%= t(:transmission, :scope => [:helpers, :label, :car]) %>:</b>
        <%= t(car.transmission || :manual , :scope => [:helpers, :label, :car])  %>
      </p>

    </div>

    <div class="span4">
      <p>
        <b><%= t(".isSmoker") %></b>
        <%= t(car.isSmoker.to_s) %>
      </p>

      <p>
        <b><%= t(".acceptedPets") %></b>
        <%= t(car.acceptedPets.to_s) %>
      </p>

      <p>
        <b><%= t(".hasGps") %></b>
        <%= t(car.hasGps.to_s) %>
      </p>

      <p>
        <b><%= t(".hasAirConditioning") %></b>
        <%= t(car.hasAirConditioning.to_s) %>
      </p>

      <p>
        <b><%= t(".hasCarRadio") %></b>
        <%= t(car.hasCarRadio.to_s) %>
      </p>

      <p>
        <b><%= t(".hasChildSeat") %></b>
        <%= t(car.hasChildSeat.to_s) %>
      </p>

    </div>

    <div class="span4">
      <p>
        <%= car.desc %>
      </p>

    </div>

  </div>

</div>

app/views/cars/_form.html.erb
<%= form_for([@user, @car]) do |f| %>
    <% if @car.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

          <ul>
            <% @car.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :brand %>
      <br/>
      <%= f.text_field :brand %>
    </div>

    <div class="field">
      <%= f.label :model %>
      <br/>
      <%= f.text_field :model %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user,@car] %> |
<%= link_to 'Back', user_cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.brand + '-' + car.model   %></td>
    <td><%= link_to 'Show', [@user,car] %></td>
    <td><%= link_to 'Edit', edit_user_car_path(@user,car) %></td>
    <td><%= link_to 'Destroy', [@user,car], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_user_car_path(@user) %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', user_cars_path(@user) %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Brand:</b>
  <%= @car.brand %>
</p>

<p>
  <b>Model:</b>
  <%= @car.model %>
</p>

<%= link_to 'Edit', edit_user_car_path(@user,@car) %> |
<%= link_to 'Back', user_cars_path %>